# Generated by Django 2.0.2 on 2018-02-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=20)),
                ('pages', models.IntegerField(default=1000)),
                ('publish_date', models.DateField()),
                ('website', models.URLField()),
                ('synopsis', models.TextField()),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
